[build]
target = "thumbv7em-none-eabi"

[target.thumbv7em-none-eabi]
rustflags = ["-C", "link-arg=-Tlink.x"]
runner = [
    "arm-none-eabi-gdb", "-q",
    "-ex", "target remote :3333",
    "-ex", "load",
    "-ex", "monitor machine Reset",
    "-ex", "maintenance flush register-cache",
    "-ex", "break *basics::main", # break in prolog of basics::main
    "-ex", "rbreak ::__cortex_m_rt_main$", # break on first line of cortex-m-rt::entry
]
